<h1>Create student</h1>
<form method='post' action=''>
    <div class="form-group">
        <label for="title">Name</label>
        <input type="text" class="form-control" id="name" placeholder="Enter a Name" name="name">
    </div>

    <div class="form-group">
        <label for="title">Email</label>
        <input type="text" class="form-control" id="email" placeholder="Enter a Email" name="email">
    </div>

    <div class="form-group">
        <label for="title">Age</label>
        <input type="text" class="form-control" id="age" placeholder="Enter a Age" name="age">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>